services:
  # Database service
  database:
    image: postgres:15-alpine
    container_name: chat-database
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - chat-network

  # Backend service (Django)
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:admin@database:5432/ecommerce
    depends_on:
      - database
    volumes:
      - ./Backend:/app
    networks:
      - chat-network

  # Frontend service (React with Vite)
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - chat-network

# Define volumes
volumes:
  postgres_data:

# Define networks
networks:
  chat-network:
    driver: bridge